# Generated by Django 3.2.3 on 2021-06-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdataapi', '0002_alter_customerdata_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='data',
        ),
        migrations.AddField(
            model_name='customerdata',
            name='SUBSCRIPTION',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'premium')], default='1', max_length=9),
        ),
    ]
