# Generated by Django 3.2.3 on 2021-06-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdataapi', '0004_auto_20210607_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='theme_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
