# Generated by Django 3.2.3 on 2021-06-07 06:17

import collections
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customerdataapi', '0005_customerdata_theme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='ENABLED_FEATURES',
            field=jsonfield.fields.JSONField(blank=True, load_kwargs={'object_pairs_hook': collections.OrderedDict}, null=True),
        ),
    ]
