# Generated by Django 3.2.3 on 2021-06-07 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdataapi', '0006_customerdata_enabled_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='SUBSCRIPTION',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium')], default='1', max_length=7, null=True),
        ),
    ]
