# Generated by Django 3.2.3 on 2021-06-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdataapi', '0007_alter_customerdata_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='language_code',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='theme_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
