# Generated by Django 3.2.3 on 2021-06-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdataapi', '0008_auto_20210607_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='LAST_PAYMENT_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='language_code',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='customerdata',
            name='theme_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
