# Generated by Django 3.2.3 on 2021-06-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdataapi', '0009_auto_20210607_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='banner_message',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='displayed_timezone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='user_profile_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
