# Generated by Django 3.2.3 on 2021-06-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdataapi', '0010_auto_20210607_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
