# Generated by Django 3.2.3 on 2021-06-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdataapi', '0011_customerdata_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdata',
            name='language_code',
            field=models.CharField(blank=True, default='en', max_length=25, null=True),
        ),
    ]
