# Generated by Django 3.2.3 on 2021-06-07 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerdataapi', '0012_alter_customerdata_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdata',
            name='DOWNGRADE_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerdata',
            name='UPGRADE_DATE',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
